### ISSUE TITLE
IG examples include code showing sample usage of the `client-js` client?

### ISSUE THREAD

**Issue by barabo** [HL7/smart-web-messaging#18]
It might be helpful to see how the `smart_messaging_origin` and `smart_web_messaging_handle` values are injected into the launch context or read on the app side.

https://docs.smarthealthit.org/client-js/

Examples in the IG illustrating application code might include logic that looks like this:
```html
<!-- index.html -->
<script src="./node_module/fhirclient/build/fhir-client.js"></script>
<script>

function launch(context) {
  const targetOrigin = context.smart_messaging_origin;
...
}

FHIR.oauth2.ready()
    .then(launch)
    .catch(console.error);
</script>
```

**Comment by barabo** [comment]
https://docs.smarthealthit.org/client-js/

**Comment by jmandel** [comment]
From the spec perspective, probably best not to depend on any specific library. Would be great in an external code sample/demo though.

**Comment by barabo** [comment]
That sounds good - I'll mark closed and plan to use the library in the codelab.
