### ISSUE TITLE
IG response HTTP status code subset could be specified

### ISSUE THREAD

**Issue by barabo** [HL7/smart-web-messaging#19]
The list of *expected* HTTP response codes could be identified, since not all of them will be relevant.

For example, the following may be the only codes expected to reasonably be encountered.

| Code | Meaning |
| --- | --- |
| 200 | OK |
| 500 | EHR Error Processing Request |
| 400 | Bad Request |
| 404 | Request Not Satisfiable (???) |
| ??? | ??? |

If there are reasonable status codes for individual request message types, it may be good to specify each of those subsets separately, too.

**Comment by jmandel** [comment]
I'm ambivalent; happy to include a couple of examples if you think it clarifies beyond the one example already in the spec.
